### ISSUE TITLE
json tree not showing

### ISSUE THREAD

**Issue by codehunter13** [Analogy-LogViewer/Analogy.LogViewer#887] opened 2021-02-24 09:35 UTC
## Describe the bug
when i paste this json in the json visualiser, the tree is not loading:
"OpenOrdersStream".OnNext([Order { ClientOrderId: "7_IGvM02Cj13_nQfnlqlHJq", Commission: 0, CommissionAsset: null, CreateTime: "0001-01-01T00:00:00.0000000", GridTradeBotId: 7, OrderId: 0, OriginalClientOrderId: "7_IGvM02Cj13_nQfnlqlHJq", Price: 1.933E-05, Quantity: 26, QuantityFilled: 0, QuoteQuantity: null, QuoteQuantityFilled: 0, Side: "Buy", Status: "Placing", Symbol: null, TradeId: 0, Type: "Limit", UpdateTime: "0001-01-01T00:00:00.0000000" }])

when i paste it in for example: http://jsonviewer.stack.hu/
the json is loaded correctly

![image](https://user-images.githubusercontent.com/7559059/108980518-09fce600-768c-11eb-9c47-8f5db56c0396.png)

OS: Windows 10
Analogy Version 4.6.1.0
serilog

**Comment by LiorBanai** [comment] 2021-02-24 09:44
Hi @codehunter13 , 
it seems not to be a valid Json. The startup text ""OpenOrdersStream".OnNext([Order" is not Json.
without it it seems ok:

![image](https://user-images.githubusercontent.com/36262995/108981545-80eaac80-7695-11eb-9fde-02cf4a7e8caa.png)


can you retest?

**Comment by codehunter13** [comment] 2021-02-24 10:27
you are right but in serilog you log like this:
logger.LogTrace("{name}.OnNext({@item})", name, item)
This gives the above output.

It would be nice to have at least an option to see this kind of message at least formatted (in a separate window/pane)
ex if you paste this in  http://jsonviewer.stack.hu/  you get it nicely formatted.

**Comment by LiorBanai** [comment] 2021-02-24 11:09
yeah it seems both issues are the same one.
Thanks for the log. I'll check this and update the visualizer/parsing

**Comment by LiorBanai** [comment] 2021-02-24 17:29
Same as the other one :)
I'll close this and fix the issue using #886 
Duplicate of #886

**Comment by LiorBanai** [comment] 2021-02-24 17:29
Duplicate of #886

**Closed by LiorBanai** 2021-02-24 17:29 UTC
