### ISSUE TITLE
Columns layout reseted after loading file

### ISSUE THREAD

**Issue by pybride** [Analogy-LogViewer/Analogy.LogViewer#1494] opened 2022-10-21 14:07 UTC
## Describe the bug
Columns layout isn't persisted between sessions

AnalogyGridlayout.xml is correctly saved after the columns layout modifications,  with the expected VisibleIndex for each column. But it is overridden when re-opening the log file.

## ℹ Computer information

 - OS: [e.g. Windows 10 Version 1909 64 bit]
 - Analogy Version 4.9.1 .NET 6
 - Data Provider used : Serilog

## 📝 Provide detailed reproduction steps (if any)

1. Open a log file (in my case a .clef)
2. Change the order of columns in the grid (or rename one header in the option)
3. Close the log tab
4. Re-open the same log file

### ✔️ Expected result

Modified columns layout should be applied

### ❌ Actual result

Default columns layout is used

**Comment by LiorBanai** [comment] 2022-10-21 14:34
Hi @pybride ,
I was not able to reproduce it. See below. 
Are my steps correct? 

![analogy_columns](https://user-images.githubusercontent.com/36262995/197220989-c93f274c-849f-414f-ae68-94b4ffc4b29e.gif)

**Comment by LiorBanai** [comment] 2022-10-21 14:39
if you load it manually what do you see (via the more-->windows layouts):
![image](https://user-images.githubusercontent.com/36262995/197222365-fa761631-9d45-49ed-b718-7c068040505c.png)

**Comment by pybride** [comment] 2022-10-24 08:07
Hi,

It works when loading a specific Windows Layout (the name is a bit misleading for me, I didn't though that it will include the column order too).
Your repro is correct, it may come from a change I didn't yet pushed.

In LogMessagesUC_Load, I added the following code near the beginning to correctly display my extension tab.

`           BookmarkModeUI();

            
            if (!string.IsNullOrEmpty(Settings.LogsLayoutFileName) && File.Exists(Settings.LogsLayoutFileName))
            {
                string name = Path.GetFileNameWithoutExtension(Settings.LogsLayoutFileName);
                wsLogs.LoadWorkspace(name, Settings.LogsLayoutFileName);
                wsLogs.ApplyWorkspace(name);
            }
            LoadWorkspace(CurrentLogLayoutFileName);


            await LoadExtensions();` 

I don't understand how that modification would override AnalogyGridlayout.xml

**Comment by LiorBanai** [comment] 2022-10-24 11:09
@pybride interesting. I'll check :)

**Comment by LiorBanai** [comment] 2022-10-24 11:10
Maybe it worth adding description (super tool tip) to the button if it misleading

**Comment by LiorBanai** [comment] 2023-04-08 12:57
@pybride Do you still experience this issue? I'm unable to reproduce it..

**Comment by LiorBanai** [comment] 2023-04-11 14:03
@pybride  what do you mean by: "but additional window for docked views is still correctly displayed" and "if the docking is correctly loaded, it should be the same for columns, but it isn't the case." 

the docking wording is not clear to me..

**Comment by pybride** [comment] 2023-04-11 14:10
by docking, I mean a secondary window with logger tree and detail view docked in it. When the corresponding layout is used, this secondary windows is correctly displayed and positioned, regardless of it is just after start, after opening a file or after re-applying the layout.

For the columns, only re-applying the layout will (re)load them correctly, otherwise is always the default ones.

**Comment by LiorBanai** [comment] 2024-12-14 15:31
closing as I was not able to reproduce it multiple tries

**Closed by LiorBanai** 2024-12-14 15:31 UTC
