### ISSUE TITLE
Not responding on start on ONE machine

### ISSUE THREAD

**Issue by pybride** [Analogy-LogViewer/Analogy.LogViewer#1528] opened 2022-11-03 16:34 UTC
## Describe the bug
I deployed Analogy.LogViewer on several machines from colleagues, and **just one** cannot start it, or it is blocked for several minutes, and then the following error is display and then everything is fine.

I tried to look at the corresponding code, but it behaves normally on my dev machine. If the issue is unknown, is it possible to get some logs from the startup?

## ℹ Computer information

 - OS: [e.g. Windows 10 Version 1909 64 bit]
 - Analogy Version 4.9.1 .NET6

## 📝 Provide detailed reproduction steps (if any)

1. Start the application

### ✔️ Expected result

The application finish the starting, and is usable

### ❌ Actual result

The application is forever not responding, or is not responding for several minutes before an error appears.

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/13061922/199777442-8550c767-6537-4f72-a6d7-3f27bcf2be21.png)

**Comment by LiorBanai** [comment] 2022-11-03 16:46
Hi @pybride 
the issue is the same ad https://github.com/Analogy-LogViewer/Analogy.LogViewer/issues/1496
I have a fix for it and plan to release it next week along with NET7 version.

Thanks for reporting it :)

**Comment by LiorBanai** [comment] 2022-11-10 18:46
Duplicate of #1496

**Comment by LiorBanai** [comment] 2022-11-10 18:46
will release new version tomorrow. Thanks for reporting

**Closed by LiorBanai** 2022-11-10 18:46 UTC
